### ISSUE TITLE
MCP Servers

### ISSUE THREAD

**Issue by slavakurilyak** [punkpeye/awesome-mcp-servers#22]
Add new MCP servers:

- https://github.com/e2b-dev/mcp-server
- https://github.com/syedazharmbnr1/ClaudeMCPServer
- https://github.com/chrishayuk/mcp-cli
- https://github.com/joshrutkowski/applescript-mcp
- https://github.com/AlexMili/Awesome-MCP
- https://github.com/petiky/awesome-mcp
- https://github.com/jlowin/fastmcp

**Comment by punkpeye** [comment]
Awesome list! Are you able to make a PR?

**Comment by slavakurilyak** [comment]
Not this time but I'm happy to share these resources
